### ISSUE TITLE
Volentix.io translation

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/volentix.github.io#4]
Enable different languages on volentix.io. It currently supports only English and Turkish; needs to support others.

**Comment by shawnlauzon** [comment]
Translation is already supported by the application; just need someone to translate the content.

Files are in the [_data/lang directory in the development branch](https://github.com/Volentix/volentix.github.io/tree/development/_data/lang); to provide a new translation:

1. Fork the repository
2. Checkout the `development` branch.
3. Create a branch for the new translation (rooted at the `development` branch)
4. Translate the content.
5. Commit the code
6. Submit a pull request.

Assigning to @Mojganahk for distribution

**Comment by shawnlauzon** [comment]
@Mojganahk You're giving the French files to Greg (helo), right?

**Comment by shawnlauzon** [comment]
Sorry @Mojganahk, that was meant for the Venue translation; he had volunteered to do it.

**Comment by Mojganahk** [comment]
Oh ok. thanks for informing. Do you want me to follow up the french version with him(Greg)?

**Comment by shawnlauzon** [comment]
@Mojganahk Definitely for Venue. For the website, I'm not sure; I suppose it wouldn't hurt to offer to him.
